### ISSUE TITLE
Operator deployment uses rolling but can never complete

### ISSUE THREAD

**Issue by kincl** [openshift/cluster-nfd-operator#107]
The operator deployment is set to `strategy: RollingUpdate` which means that when an update is rolled out the pods in the new ReplicaSet have to go ready before the old ReplicaSet is scaled down. This creates a deadlock scenario:

- deployment rolls out new version
- a new RS is created which creates a new operator pod
- new operator pod sees controller lock and waits for lease to expire
- old operator pod is never scaled down and maintains lock

My fix is to just manually scale down the old RS which fixes everything but I think the best answer would be for the operator Deployment to be set to `strategy: recreate`

**Comment by niconosenzo** [comment]
@ArangoGutierrez are you working on this already ? Otherwise I would like to take over if you don't mind :smile:

**Comment by ArangoGutierrez** [comment]
Not at  all happy to help! 
/assign niconosenzo

**Comment by ArangoGutierrez** [comment]
@ niconosenzo you still taking on this, or should I take it?

**Comment by niconosenzo** [comment]
@ArangoGutierrez should be solved by [this PR](https://github.com/openshift/cluster-nfd-operator/pull/116).
