### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by cfilleke** [openshift/cluster-nfd-operator#119]
Since this and https://github.com/openshift/node-feature-discovery are the two repositories linked to in the operator as deployed in OperatorHub, it would be useful to have more explicit instructions here as to what a user, having subscribed to the operator through the CLI as described in https://docs.openshift.com/container-platform/4.6/operators/admin/olm-adding-operators-to-cluster.html#olm-installing-operator-from-operatorhub-using-cli_olm-adding-operators-to-a-cluster, would do next to instantiate and configure the server & worker pods in a particular namespace.  

For the record, all the user need do to instantiate the server and worker pods is `oc apply -f 0700_cr.yaml` with the namespace specified, and the configuration instructions are in https://kubernetes-sigs.github.io/node-feature-discovery/v0.7/get-started/deployment-and-usage.html#configuration

**Comment by ArangoGutierrez** [comment]
Thanks for this issue, we will make this part of next sprint work

**Comment by cfilleke** [comment]
There's a related issue opened in https://github.com/openshift/openshift-docs/issues/28402

**Comment by ArangoGutierrez** [comment]
Being worked now upstream https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/50

**Comment by ArangoGutierrez** [comment]
Issue being worked
we now have a website for docs! 

https://kubernetes-sigs.github.io/node-feature-discovery-operator/master/

**Comment by cfilleke** [comment]
Thanks, Eduardo! :)
