### ISSUE TITLE
Could not install NodeFeatureDiscovery on OKD4.5 and 4.6 Cluster by operatorHub.

### ISSUE THREAD

**Issue by rupang790** [openshift/cluster-nfd-operator#144]
On my OKD Cluster, I found the NFD operator on operatorHub, so I tried to install it from operatorHub.
But It was not installed.
(Before I found it on operatorHub, I used to install it manually, which I cloned from git and use ```make``` command to deploy.)

Installation proceeded in two ways ( Install on All Namespaces-default / specific Namespace ), but the following error occurred:
![image](https://user-images.githubusercontent.com/40801176/111579516-7be2ce00-87f9-11eb-8282-ffe41b0e3d44.png)

```
{"level":"info","ts":1616045944.9220765,"logger":"cmd","msg":"Go Version: go1.15.5"}
{"level":"info","ts":1616045944.9221418,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1616045944.9221659,"logger":"cmd","msg":"Version of operator-sdk: v0.4.0+git"}
{"level":"info","ts":1616045944.922823,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1616045946.8118556,"logger":"leader","msg":"No pre-existing lock was found."}
{"level":"info","ts":1616045946.8415146,"logger":"leader","msg":"Became the leader."}
{"level":"info","ts":1616045950.8142676,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1616045950.8169394,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1616045950.817697,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1616045950.818323,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1616045950.8187845,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1616045950.8190293,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1616045950.8192632,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1616045950.8194685,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1616045950.8199208,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1616045950.8208203,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1616045950.8210897,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1616045950.8213153,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1616045950.821549,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1616045950.8217416,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1616045950.8219752,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1616045950.8221507,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"nodefeaturediscovery-controller"}
{"level":"info","ts":1616045951.0225158,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"nodefeaturediscovery-controller","worker count":1}
```

How can I solve this? Do anyone have same error with?

**Comment by lgc0313** [comment]
same error on ocp 4.6.19

**Comment by ArangoGutierrez** [comment]
Hi @lgc0313  I am going to fix this today, looks like the community operator on OperatorHub is outdated

**Comment by lgc0313** [comment]
@ArangoGutierrez Thanks.Waiting for repair online

**Comment by ArangoGutierrez** [comment]
https://github.com/operator-framework/community-operators/pull/3402 is merged, give it a day to roll out, all fixes should be in place now

**Comment by lgc0313** [comment]
@ArangoGutierrez There is still the same issue now.

**Comment by ArangoGutierrez** [comment]
Hi @rupang790 @lgc0313 is this still an issue? 
if so, would you let me know the versions of your cluster, and version of the operatorhub?

**Comment by rupang790** [comment]
Hi, @ArangoGutierrez 
on my OKD Cluster (4.6.0-0.okd-2021-02-14-205305) It is installed well through operatorHub.
I used NFD version 4.7 and It works for me. For @lgc0313, I will not close this issue.

However, if I would like to install Special-Resource-operator, should I delete NFD-operator for it?
(Because It saw Special-Resource-Operator install NFD itself again.)

Thank you for fix the issue.

**Comment by ArangoGutierrez** [comment]
for SRO let's ask @dagrayvid

**Comment by dagrayvid** [comment]
Hi @rupang790, we shouldn't need to uninstall NFD before installing SRO. I think the reason that it would have been installing NFD again is because SRO's dependency on NFD was out-of-date and looking for an NFD version older than 4.7, hence it was installing 4.5 or 4.6 in addition to the already installed NFD 4.7. This was updated last Friday [in communityoperators](https://github.com/operator-framework/community-operators/pull/3592) and should be updated in the next few days, if it wasn't already. 

Let me know if you have any questions.

**Comment by rupang790** [comment]
@dagrayvid, I tried to install SRO on my cluster but it seems not installing status.
I used OperatorHub to install and check NFD version as 4.7.
![image](https://user-images.githubusercontent.com/40801176/115362309-5bdd6a80-a1fc-11eb-98c3-a47e481127d7.png)
![image](https://user-images.githubusercontent.com/40801176/115362334-626be200-a1fc-11eb-969b-6a51c1d00cae.png)

Do there have any logs about installation of operators? 
One more thing is, Is SRO could be installed when GPU device existed on Node? 

If I should create new Issue about this on SRO GitHub, please tell me. 
Thank you for comment.

**Comment by dagrayvid** [comment]
Hi @rupang790 I haven't seen this error before, so I will have to investigate. Please open an issue on the [upstream SRO GitHub](https://github.com/openshift-psap/special-resource-operator/) to track this. 

Is this on OKD? Having GPU devices on the node should not cause any problems.

**Comment by paravatha** [comment]
I am trying install NFD 4.7 on OCP 4.6.26, but getting this error

![image](https://user-images.githubusercontent.com/8755869/127691791-db9c41d7-b205-435c-bcfc-ce53b4d4f54c.png)

@rupang790 @dagrayvid were you able to get this working?
