### ISSUE TITLE
OCP build error: CSV annotations cannot be null

### ISSUE THREAD

**Issue by vfreex** [openshift/cluster-nfd-operator#146]
Bundle build for cluster-nfd-operator is failing on OSBS. It seems to me that OSBS introduced a check and disallows null values in annotations.
https://github.com/openshift/cluster-nfd-operator/blob/110fdc7dc426669aa306d9e78eb2067bdf4bb0d3/manifests/olm-catalog/4.7/nfd.v4.7.0.clusterserviceversion.yaml#L15 is empty. We need to either give it a value to use an empty string `""`, though I am not sure if the check will allow empty strings or not.

**Comment by thegreyd** [comment]
This seems to be resolved now (or soon), see
- https://github.com/openshift/cluster-nfd-operator/pull/147
- https://github.com/openshift/cluster-nfd-operator/pull/148
- https://github.com/openshift/cluster-nfd-operator/pull/149

**Comment by ArangoGutierrez** [comment]
@vfreex  could you confirm that this issue has been solved? 
if so can we close this issue, 
thanks!
