### ISSUE TITLE
The proper way to deploy NFD on OCP through NFD-operator

### ISSUE THREAD

**Issue by Walnux** [openshift/cluster-nfd-operator#231]
Our operator running on OCP depends on NFD and needs to deploy NFD with some specific configurations. We'd like to know what is the proper way for us to deploy NFD through NFD-operator on OCP.

We plan to add NFD-operator as a dependency into our operator Bundle image metadata and let our operator create a CR including our configuration from NFD-operator CRD and deploy NFD.

But the potential problem is that if some other users on the same cluster also do the same thing and create their CRs. Can these CRs coexist? 

If these CRs can't coexist, does that mean we need a cluster Administrator to merge the different requirements from users manually and create CR to deploy NFD?

Any suggestions and help are appreciated!

**Comment by ArangoGutierrez** [comment]
Hi! 
the official documentation can be found at:
- https://docs.openshift.com/container-platform/4.9/hardware_enablement/psap-node-feature-discovery-operator.html 

You can check how projects like https://github.com/openshift/special-resource-operator have dependency on NFD, and how they install it as part of the CSV install plan.  (https://github.com/openshift/special-resource-operator/blob/master/config/manifests/bases/openshift-special-resource-operator.clusterserviceversion.yaml#L28)
