### ISSUE TITLE
OLM-installed nfd.v4.10.0's nfd-controller-manager fails to start

### ISSUE THREAD

**Issue by ibotty** [openshift/cluster-nfd-operator#264]
```
❯ oc logs -n openshift-nfd nfd-controller-manager-576765f974-krxgc -c manager
I0622 11:03:24.298094       1 main.go:61] Operator Version: a42b581a-dirty
2022-06-22T11:03:24.298Z        DPANIC  setup   non-string key argument passed to logging, ignoring all later arguments {"invalid key": "POD_NAMESPACE must be set"}
panic: non-string key argument passed to logging, ignoring all later arguments

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00002e300, {0xc00036ee00, 0x1, 0x1})
        /go/src/github.com/openshift/cluster-nfd-operator/vendor/go.uber.org/zap/zapcore/entry.go:232 +0x446
go.uber.org/zap.(*Logger).DPanic(0x15de809, {0x163560e, 0x14170a0}, {0xc00036ee00, 0x1, 0x1})
        /go/src/github.com/openshift/cluster-nfd-operator/vendor/go.uber.org/zap/logger.go:220 +0x59
github.com/go-logr/zapr.handleFields(0x0, {0xc000255480, 0x2, 0x40cfe7}, {0x0, 0x0, 0xc000217b01})
        /go/src/github.com/openshift/cluster-nfd-operator/vendor/github.com/go-logr/zapr/zapr.go:110 +0x3f1
github.com/go-logr/zapr.(*zapLogger).WithValues(0xc0004cd5a0, {0xc000255480, 0x1, 0x15df7c6})
        /go/src/github.com/openshift/cluster-nfd-operator/vendor/github.com/go-logr/zapr/zapr.go:145 +0x31
main.main()
        /go/src/github.com/openshift/cluster-nfd-operator/main.go:130 +0x3e2
```

Setting `POD_NAMESPACE` via downwards API and it starts successfully.
I don't know why it was missing from my installation.

**Comment by rupang790** [comment]
Is there any update for this? I could not use NFD installed by OLM.
@ibotty, 
How did you put the `POD_NAMESPACE` ?
> ```
> ❯ oc logs -n openshift-nfd nfd-controller-manager-576765f974-krxgc -c manager
> I0622 11:03:24.298094       1 main.go:61] Operator Version: a42b581a-dirty
> 2022-06-22T11:03:24.298Z        DPANIC  setup   non-string key argument passed to logging, ignoring all later arguments {"invalid key": "POD_NAMESPACE must be set"}
> panic: non-string key argument passed to logging, ignoring all later arguments
> 
> goroutine 1 [running]:
> go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00002e300, {0xc00036ee00, 0x1, 0x1})
>         /go/src/github.com/openshift/cluster-nfd-operator/vendor/go.uber.org/zap/zapcore/entry.go:232 +0x446
> go.uber.org/zap.(*Logger).DPanic(0x15de809, {0x163560e, 0x14170a0}, {0xc00036ee00, 0x1, 0x1})
>         /go/src/github.com/openshift/cluster-nfd-operator/vendor/go.uber.org/zap/logger.go:220 +0x59
> github.com/go-logr/zapr.handleFields(0x0, {0xc000255480, 0x2, 0x40cfe7}, {0x0, 0x0, 0xc000217b01})
>         /go/src/github.com/openshift/cluster-nfd-operator/vendor/github.com/go-logr/zapr/zapr.go:110 +0x3f1
> github.com/go-logr/zapr.(*zapLogger).WithValues(0xc0004cd5a0, {0xc000255480, 0x1, 0x15df7c6})
>         /go/src/github.com/openshift/cluster-nfd-operator/vendor/github.com/go-logr/zapr/zapr.go:145 +0x31
> main.main()
>         /go/src/github.com/openshift/cluster-nfd-operator/main.go:130 +0x3e2
> ```
> 
> 
>     
>  
>   
> 
> Setting `POD_NAMESPACE` via downwards API and it starts successfully.
> I don't know why it was missing from my installation.

**Comment by ibotty** [comment]
I don't exactly remember, but I have the following block in my `nfd-controller-manager` `deployment`:
```
[...]
         env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
```

**Comment by bthurber** [comment]
@yevgeny-shnaidman I believe we can close this as we are beyond OCP 4.10 lifecycle support.
