### ISSUE TITLE
A way to customize the deployment

### ISSUE THREAD

**Issue by MarSik** [openshift/cluster-nfd-operator#3]
We would like deploy the NFD service using the operator, but with some customization done (additional plugins and related pods). You can find the way we do that here https://github.com/ksimon1/cpu-model-nfd-plugin/blob/master/cpu-model-nfd-plugin.yaml.template

The issue is, there is no way to configure NFD when it is deployed and started using this operator.

The basic requirements are:
- a empty{} volume for plugins mounted to /etc/kubernetes/node-feature-discovery/source.d/
- list of extra containers to populate the plugin volume in the initContainers section
- list of extra containers to run alongside NFD with that plugin volume mounted to a well known location
 
We can use our custom deployment and manage the lifecycle ourselves, but we would lose the changes provided by this operator and it would not be vanilla openshift anymore.

**Comment by ArangoGutierrez** [comment]
PR https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/39 is a first step towards this issue

**Comment by ArangoGutierrez** [comment]
@MarSik is this issue still a need for you, current NFD-Operator is more configurable than before, maybe it now attend your needs 
/remove-lifecycle stale

**Comment by ArangoGutierrez** [comment]
@MarSik the current `master` branch version of the operator is more customizable than before (when this issue was filed) 
Do we still need this issue or can we close it?
