### ISSUE TITLE
4.3 olm data needs to be updated

### ISSUE THREAD

**Issue by jupierce** [openshift/cluster-nfd-operator#30]
https://github.com/openshift/cluster-nfd-operator/tree/release-4.3/manifests/olm-catalog
file does not exist: manifests/olm-catalog/4.3/image-references

**Comment by zvonkok** [comment]
https://github.com/openshift/cluster-nfd-operator/pull/32

**Comment by zvonkok** [comment]
New PR the other was with some leftovers, https://github.com/openshift/cluster-nfd-operator/pull/33

**Comment by zvonkok** [comment]
@jupierce I am unsure about the correct nfd.package.yaml syntax, can you take a look?
Haven't found any reference from other operators.

**Comment by zvonkok** [comment]
Removed the 4.2 references, @jupierce ignore my previous comment.

**Comment by zvonkok** [comment]
Merged: https://github.com/openshift/cluster-nfd-operator/pull/33
