### ISSUE TITLE
OpenShift NFD --enable-taints option not supported

### ISSUE THREAD

**Issue by vbedida79** [openshift/cluster-nfd-operator#356]
### Summary
OpenShift NFD operator version 4.14.0-202402081809  on OCP 4.14.11, does not support `--enable-taints` feature. 

### Details
We are currently creating accelerator profiles on OpenShift AI for multiple Intel GPU cards through taints- as mentioned in [RH accelerator profile doc](https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science_self-managed/2.4/html/working_on_data_science_projects/working-with-accelerators_accelerators#creating-an-accelerator-profile_accelerators) Current accelerator profile for one of the Intel GPU cards- [link](https://github.com/intel/intel-technology-enabling-for-openshift/blob/main/e2e/inference/accelerator_profile.yaml).  Tolerations are already supported in accelerator profile.

 For multiple GPU cards support, we would need to add taints on the nodes using NFD operator's NodeFeatureRule instance to integrate and use the accelerator profiles with Intel GPU device plugin's resource. We cannot directly taint the node as we do need `matchFeatures` with taints from NodeFeatureRule.
 According to [NFD upstream document](https://nfd.sigs.k8s.io/usage/customization-guide#node-tainting ) tainting seems to be an experimental feature. We have tried adding _--enable-taints_ in the nfd-worker pods/daemonset manually but this command is not supported. 

Is it possible to enable this feature on OCP 4.14? If not, when would it be supported on OCP? Thanks!

**Comment by uMartinXu** [comment]
https://github.com/intel/intel-technology-enabling-for-openshift/issues/216 rely on this issue
