### ISSUE TITLE
Please prepare bundle for OCP 4.4

### ISSUE THREAD

**Issue by sosiouxme** [openshift/cluster-nfd-operator#41]
Now that we are fully branched for 4.4, please prepare your operator to supply a 4.4 bundle, so that 4.4 operator publishing works and doesn't overwrite 4.3 bundles. This means at least updating the package.yaml under https://github.com/openshift/cluster-nfd-operator/tree/master/manifests
@zvonkok

**Comment by zvonkok** [comment]
Merged https://github.com/openshift/cluster-nfd-operator/pull/42
