### ISSUE TITLE
NFD Operator on OperatorHub not installing

### ISSUE THREAD

**Issue by madorn** [openshift/cluster-nfd-operator#54]
Description of problem:

After installing NFD Operator, pods keep crashing. 

`{"level":"info","ts":1579886681.9943285,"logger":"cmd","msg":"Go Version: go1.12.12"}
{"level":"info","ts":1579886681.9943712,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1579886681.9943788,"logger":"cmd","msg":"Version of operator-sdk: v0.4.0+git"}
{"level":"info","ts":1579886681.9950516,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1579886682.1206093,"logger":"leader","msg":"Found existing lock with my name. I was likely restarted."}
{"level":"info","ts":1579886682.120643,"logger":"leader","msg":"Continuing as the leader."}
{"level":"info","ts":1579886682.2016144,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1579886682.2017787,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1579886682.2019343,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1579886682.202073,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1579886682.2021816,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1579886682.20229,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"error","ts":1579886682.202312,"logger":"cmd","msg":"","error":"no kind is registered for the type v1.SecurityContextConstraints in scheme \"k8s.io/client-go/kubernetes/scheme/register.go:60\"","stacktrace":"github.com/openshift/cluster-nfd-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/openshift/cluster-nfd-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/go/src/github.com/openshift/cluster-nfd-operator/cmd/manager/main.go:92\nruntime.main\n\t/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:200"}`

Upon first glance, controller appears to be attempting to watch `/api/v1/securitycontextconstraints` which is not available in OpenShift 4.x.

The OperatorHub controller image should be updated to watch `/apis/security.openshift.io/v1/securitycontextconstraints`.

**Comment by ArangoGutierrez** [comment]
Hi @madorn , could you try the [namescpace-scoped](https://github.com/openshift/cluster-nfd-operator/tree/namespace-scoped) branch?, although it has been merged now into master, it had the fix for the SCC API issue

**Comment by madorn** [comment]
@ArangoGutierrez Hi Carlos, thank you!!

can we can get this change committed to the image that currently resides in OpenShift 4x? It is located at `registry.redhat.io/openshift4/ose-cluster-nfd-operator@sha256:ff782d4c2a3c9436ea9d9713cd6e360337aebdf8c9d6f02d1c4d07ba305de847`

If you need assistance pushing the commit there, happy to help!

**Comment by ArangoGutierrez** [comment]
is now on master, we can close this issue

**Comment by madorn** [comment]
@ArangoGutierrez Thanks Carlos.

Will the image will be pushed here?: https://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/openshift4/ose-cluster-nfd-operator

**Comment by ArangoGutierrez** [comment]
Heya @madorn , is it working for you? or do we need some extra work here :)

**Comment by jaypal17** [comment]
I'm experiencing the a similar issue when installing through the web console on openshift. 
My environment:
crc version: 1.6.0+8ef676f
OpenShift version: 4.3.0
Error msg I get:
Failed: install failed: Timeout: deployment nfd-operator not ready before timeout: deployment "nfd-operator" exceeded its progress deadline
I also see this:
installing: Waiting: waiting for deployment nfd-operator to become ready: Waiting for rollout to finish: 0 of 1 updated replicas are available...

**Comment by madorn** [comment]
> Heya @madorn , is it working for you? or do we need some extra work here :)

Yes it is working now!

**Comment by madorn** [comment]
> I'm experiencing the a similar issue when installing through the web console on openshift.
> My environment:
> crc version: 1.6.0+8ef676f
> OpenShift version: 4.3.0
> Error msg I get:
> Failed: install failed: Timeout: deployment nfd-operator not ready before timeout: deployment "nfd-operator" exceeded its progress deadline
> I also see this:
> installing: Waiting: waiting for deployment nfd-operator to become ready: Waiting for rollout to finish: 0 of 1 updated replicas are available...

Jay, I don't think Node Discovery will run on CRC.....needs to be multi-node environment, i.e. master and work nodes properly labeled.

**Comment by mythi** [comment]
Is this expected to work on vanilla kubernetes? I get the same error as originally reported.

**Comment by madorn** [comment]
@mythi how did you install the Operator on the vanilla kubernetes cluster? Is OLM installed in the cluster?

**Comment by mythi** [comment]
@madorn I used `make deploy` based on instructions in the `README`.  What is OLM?

**Comment by madorn** [comment]
@mythi https://github.com/operator-framework/operator-lifecycle-manager

**Comment by mythi** [comment]
@madorn ah, thanks I had that missing but even with that the same error occurs:

```
$ kubectl logs nfd-operator-5ffb978c7c-pv64k -n openshift-nfd
{"level":"info","ts":1585594183.2338152,"logger":"cmd","msg":"Go Version: go1.13.8"}
{"level":"info","ts":1585594183.2338634,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1585594183.2338767,"logger":"cmd","msg":"Version of operator-sdk: v0.4.0+git"}
{"level":"info","ts":1585594183.2342427,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1585594183.2773724,"logger":"leader","msg":"Found existing lock with my name. I was likely restarted."}
{"level":"info","ts":1585594183.2774174,"logger":"leader","msg":"Continuing as the leader."}
{"level":"info","ts":1585594183.7321594,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1585594183.73271,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1585594183.7331934,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1585594183.7336092,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1585594183.733983,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1585594183.7342155,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1585594183.7343142,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1585594183.7344038,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1585594183.7346737,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"error","ts":1585594185.6808777,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"SecurityContextConstraints.security.openshift.io","error":"no matches for kind \"SecurityContextConstraints\" in version \"security.openshift.io/v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/openshift/cluster-nfd-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/go/src/github.com/openshift/cluster-nfd-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:88\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/openshift/cluster-nfd-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:165\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/src/github.com/openshift/cluster-nfd-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:198\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startLeaderElectionRunnables.func1\n\t/go/src/github.com/openshift/cluster-nfd-operator/vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go:477"}
{"level":"error","ts":1585594185.6810625,"logger":"cmd","msg":"Manager exited non-zero","error":"no matches for kind \"SecurityContextConstraints\" in version \"security.openshift.io/v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/openshift/cluster-nfd-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/go/src/github.com/openshift/cluster-nfd-operator/cmd/manager/main.go:106\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
```

**Comment by madorn** [comment]
@mythi The Operator you are attempting to install only works on an OpenShift environment - you can see the Operator is looking for `"kind":"SecurityContextConstraints.security.openshift.io"`.

This endpoint is only found in Openshift environments.

I am going to close this issue but please open new issue and specify the type of Kubernetes distribution you are using and Kubernetes version and error.

**Comment by mythi** [comment]
> please open new issue and specify the type of Kubernetes distribution you are using and
> Kubernetes version and error.

I can work without the operator and deploy NFD manually for now but it'd be really nice if this had the option to deploy on vanilla kubernetes too (my setup is just a barametal kubeadm install).
