### ISSUE TITLE
Please prepare bundle for OCP 4.5

### ISSUE THREAD

**Issue by tbielawa** [openshift/cluster-nfd-operator#71]
Now that we are fully branched for 4.5, please prepare your operator to supply a 4.5 bundle, so that 4.5 operator publishing works and doesn't overwrite 4.4 bundles. This means at least updating the package.yaml under https://github.com/openshift/cluster-nfd-operator/blob/master/manifests/olm-catalog/nfd.package.yaml

Reference: [Get OLM operator owners to update their CSV channels](https://issues.redhat.com/browse/ART-1559)

**Comment by tbielawa** [comment]
Looks like the required changes were made in this commit? https://github.com/openshift/cluster-nfd-operator/commit/8043abefef08a714716f546c707cf41e47eee4e1

**Comment by tbielawa** [comment]
@zvonkok or @ArangoGutierrez any feedback on this?

**Comment by ArangoGutierrez** [comment]
#75 

This PR is part of the effort to prepare a fully functional 4.5 branch

**Comment by ArangoGutierrez** [comment]
@tbielawa #75 is now merged

**Comment by tbielawa** [comment]
Thanks!
