### ISSUE TITLE
nfd-workers crashes under an ipv6 environment

### ISSUE THREAD

**Issue by yrobla** [openshift/cluster-nfd-operator#80]
I applied this operator on an environment with ipv6. It deployed correctly on masters, but nfd-workers pods keep crashing.
When i look at logs inside the container, i can see:

2020/04/08 10:44:05 Sendng labeling request nfd-master
2020/04/08 10:44:05 failed to set node labels: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: address fd02::d19a:12000: too many colons in address"

This seems to be a problem with ipv6 address validation.

**Comment by zvonkok** [comment]
@yrobla This is a operand issue not an operator issue. Can you please create the issue on [https://github.com/kubernetes-sigs/node-feature-discovery/issues](https://github.com/kubernetes-sigs/node-feature-discovery/issues) , this is the upstream version, I need to fix it first there.

**Comment by yrobla** [comment]
Ok i created: https://github.com/kubernetes-sigs/node-feature-discovery/issues/301
