### ISSUE TITLE
Customizing nfd-worker's config

### ISSUE THREAD

**Issue by patrykxmatuszak** [openshift/cluster-nfd-operator#99]
Hi,

Is there's any way to customize the nfd-worker's config without building own images?
I wanted to change the labels from vendor to vendor+device id (and possible other), but it seems that after editing `configmap -n openshift-nfd nfd-worker` operator immediately overwrites with the definition embedded in its container image.

Thanks

**Comment by zvonkok** [comment]
@ArangoGutierrez PTAL

**Comment by patrykxmatuszak** [comment]
What is status of the issue? It's rather important for us.

**Comment by ArangoGutierrez** [comment]
Hi @patrykxmatuszak I am currently working on this on the upstream NFD https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/36 hope soon will be merged and ported into the OpenShift distribution

**Comment by ArangoGutierrez** [comment]
@patrykxmatuszak -> https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/39

once merged upstream, I will try to backport it as soon as I can

**Comment by ArangoGutierrez** [comment]
Current master now expands the NodeFeatureDiscovery CRD to enable users  to modify the CR and define the `nfd-worker-conf` , or if the operator has already been deployed, users will be able to modify the CR

**Comment by ArangoGutierrez** [comment]
@patrykxmatuszak please let us know if current master satisfy your use case so we can close this issue :) 
thanks for your interest in the project

**Comment by ArangoGutierrez** [comment]
@patrykxmatuszak now you can edit and customize nfd-worker config via CR NodeFeatureDiscovery 
Is that ok for you, if so can we close this issue
thanks
